global_scale = 0.4000000059604645
anchor_name = "bottom_left"
font = "futura-book-bt.ttf"
font_size = 40.0
# The size of the hud, in pixels. Will be scaled.
size = { x = 800.0, y = 800.0 }

# The color of the HUD background file. Set alpha to 0 to skip drawing a background.
bg_color = { r = 0, g = 0, b = 0, a = 64 }
# Only draw the ammo slot when a weapon that uses ammo (ranged) is equipped.
hide_ammo_when_irrelevant = true
# Hide the left hand slot when a ranged weapon is equipped. This lets you
# use the same location as the left hand to show ammo.
hide_left_when_irrelevant = true

chinese_full_glyphs = false
simplified_chinese_glyphs = false
cyrillic_glyphs = false
japanese_glyphs = false
korean_glyphs = false
thai_glyphs = false
vietnamese_glyphs = false

# This is the sub-layout for the shouts and powers slot.
[[layouts]]
# This name is to help humans editing this file figure out which slot they're on.
# It's not drawn in the HUD.
name = "Shouts/Powers"
# Used to help the hud renderer figure out which slot this is. Complicated
# handwave about serializing TOML. You must not change this number, but you can ignore it.
element = { repr = 0 }
# The offset of the center of this slot relative to the center of the HUD.
# This gets scaled when the global scaling factor is applied.
offset = { x = -230.0, y = -230.0 }
# Size of this slot, before scaling.
size = { x = 300.0 , y = 300.0 }
# How to align name and count text for this slot.
align_text = "center"

# The color to use to draw this slot's background. Alpha of 0 means it's not visible.
# Color is expressed as RGBA; values are 0-255.
bg_color = { r = 255, g = 255, b = 255, a = 128 }
# Color for this HUD's icon. Alpha of 0 means it's not drawn. The icon is
# always centered in the slot.
icon_color = { r = 200, g = 200, b = 200, a = 255 }
# Size of the icon for this slot, before scaling.
icon_size = { x = 175.0, y = 175.0 }

# Color for this HUD's hotkey. Alpha of 0 means it's not drawn.
hotkey_color = { r = 255, g = 255, b = 255, a = 255 }
# Where to draw the hotkey. Gets scaled.
hotkey_offset = { x = 190.0, y = 0.0 }
# Size of the hotkey. Also scaled.
hotkey_size = { x = 60.0, y = 60.0 }
# Background color for the hotkey. Alpha means invisible.
hotkey_bg_color = { r = 0, g = 0, b = 0, a = 0 }

# Offset for any count text. Gets scaled.
count_offset = { x = 0.0, y = 0.0 }
# The color for any count displays. An alpha of 0 means not drawn.
count_color = { r = 200, g = 200, b = 200, a = 255 }
# Font size for item count.
count_font_size = 40.0

# The color for the name text of any item in this slot.
name_color = { r = 255, g = 255, b = 255, a = 255 }
# Where to draw the item name. Gets scaled.
name_offset = { x = 0.0, y = 160.0 }
# Font size for the item name.
name_font_size = 50.0

# The consumables slot. You can change all of these values
# independently from the other slots.
[[layouts]]
name = "Consumables"
align_text = "center"
element = { repr = 1 }
offset = { x = 230.0, y = -230.0 }
size = { x = 300.0 , y = 300.0 }
bg_color = { r = 255, g = 255, b = 255, a = 128 }
icon_color = { r = 200, g = 200, b = 200, a = 255 }
icon_size = { x = 175.0, y = 175.0 }
icon_offset = { x = 0.0, y = 0.0 }

hotkey_color = { r = 255, g = 255, b = 255, a = 255 }
hotkey_offset = { x = -190.0, y = 0.0 }
hotkey_size = { x = 60.0, y = 60.0 }
hotkey_bg_color = { r = 255, g = 255, b = 255, a = 0 }

count_font_size = 60.0
count_offset = { x = 0.0, y = 0.0 }
count_color = { r = 255, g = 255, b = 255, a = 255 }

name_font_size = 50.0
name_color = { r = 255, g = 255, b = 255, a = 255 }
name_offset = { x = 0.0, y = 160.0 }

[[layouts]]
name = "Left Hand"
element = { repr = 2 }
size = { x = 300.0 , y = 300.0 }
offset = { x = -230.0, y = 230.0 }
bg_color = { r = 255, g = 255, b = 255, a = 128 }
align_text = "center"

icon_color = { r = 200, g = 200, b = 200, a = 255 }
icon_size = { x = 175.0, y = 175.0 }
icon_offset = { x = 0.0, y = 0.0 }

hotkey_color = { r = 255, g = 255, b = 255, a = 255 }
hotkey_offset = { x = 190.0, y = 0.0 }
hotkey_size = { x = 60.0, y = 60.0 }
hotkey_bg_color = { r = 255, g = 255, b = 255, a = 0 }

count_offset = { x = 0.0, y = -210.0 }
count_font_size = 40.0
count_color = { r = 255, g = 255, b = 255, a = 255 }

name_font_size = 50.0
name_color = { r = 255, g = 255, b = 255, a = 255 }
name_offset = { x = 0.0, y = -210.0 }


[[layouts]]
name = "Right Hand"
align_text = "center"
element = { repr = 3 }
offset = { x = 230.0, y = 230.0 }
size = { x = 300.0 , y = 300.0 }
bg_color = { r = 255, g = 255, b = 255, a = 128 }
icon_color = { r = 200, g = 200, b = 200, a = 255 }
icon_size = { x = 175.0, y = 175.0 }
icon_offset = { x = 0.0, y = 0.0 }
hotkey_color = { r = 255, g = 255, b = 255, a = 255 }
hotkey_bg_color = { r = 255, g = 255, b = 255, a = 0 }
hotkey_offset = { x = -190.0, y = 0.0 }
hotkey_size = { x = 60.0, y = 60.0 }
count_font_size = 40.0
count_offset = { x = 0.0, y = 0.0 }
count_color = { r = 255, g = 255, b = 255, a = 255 }
name_font_size = 50.0
name_color = { r = 255, g = 255, b = 255, a = 255 }
name_offset = { x = 0.0, y = -210.0 }

[[layouts]]
name = "Ammo"
element = { repr = 4 }
size = { x = 300.0 , y = 300.0 }
offset = { x = -230.0, y = 230.0 }
bg_color = { r = 255, g = 255, b = 255, a = 128 }
align_text = "center"

icon_color = { r = 200, g = 200, b = 200, a = 255 }
icon_size = { x = 175.0, y = 175.0 }
icon_offset = { x = 0.0, y = 0.0 }

hotkey_color = { r = 255, g = 255, b = 255, a = 255 }
hotkey_offset = { x = 190.0, y = 0.0 }
hotkey_size = { x = 60.0, y = 60.0 }
hotkey_bg_color = { r = 255, g = 255, b = 255, a = 0 }

count_offset = { x = 0.0, y = -210.0 }
count_font_size = 40.0
count_color = { r = 255, g = 255, b = 255, a = 255 }

name_font_size = 50.0
name_color = { r = 255, g = 255, b = 255, a = 255 }
name_offset = { x = 0.0, y = -210.0 }
