animation_alpha = 51
animation_duration = 0.2
font = "futura-book-bt.ttf"
font_size = 20.0
debug = false

[anchor]
x = 150.0
y = 1350.0

[size]
x = 400.0
y = 400.0

[bg_color]
r = 255
g = 255
b = 255
a = 128

[[layouts]]
name = "Shouts/Powers"
count_font_size = 15.0

[layouts.element]
repr = 0

[layouts.offset]
x = 0.0
y = -111.0

[layouts.size]
x = 125.0
y = 125.0

[layouts.bg_color]
r = 255
g = 255
b = 255
a = 0

[layouts.icon_color]
r = 200
g = 200
b = 200
a = 255

[layouts.icon_size]
x = 81.0
y = 81.0

[layouts.hotkey_color]
r = 255
g = 255
b = 255
a = 255

[layouts.hotkey_offset]
x = 0.0
y = 225.0

[layouts.hotkey_size]
x = 30.0
y = 30.0

[layouts.hotkey_bg_color]
r = 255
g = 255
b = 255
a = 100

[layouts.text_offset]
x = 0.0
y = 0.0

[layouts.count_color]
r = 255
g = 255
b = 255
a = 255

[layouts.name_color]
r = 255
g = 255
b = 255
a = 255

[layouts.name_offset]
x = 0.0
y = 20.0

[[layouts]]
name = "Consumables"
count_font_size = 20.0

[layouts.element]
repr = 1

[layouts.offset]
x = 0.0
y = 446.0

[layouts.size]
x = 125.0
y = 125.0

[layouts.bg_color]
r = 255
g = 255
b = 255
a = 0

[layouts.icon_color]
r = 200
g = 200
b = 210
a = 255

[layouts.icon_size]
x = 81.0
y = 81.0

[layouts.hotkey_color]
r = 255
g = 255
b = 255
a = 255

[layouts.hotkey_offset]
x = 0.0
y = -225.0

[layouts.hotkey_size]
x = 30.0
y = 30.0

[layouts.hotkey_bg_color]
r = 255
g = 255
b = 255
a = 100

[layouts.text_offset]
x = 0.0
y = 0.0

[layouts.count_color]
r = 255
g = 255
b = 255
a = 255

[layouts.name_color]
r = 255
g = 255
b = 255
a = 255

[layouts.name_offset]
x = 0.0
y = 20.0

[[layouts]]
name = "Left Hand"
count_font_size = 20.0

[layouts.element]
repr = 2

[layouts.offset]
x = -446.0
y = 0.0

[layouts.size]
x = 125.0
y = 125.0

[layouts.bg_color]
r = 255
g = 255
b = 255
a = 100

[layouts.icon_color]
r = 200
g = 200
b = 210
a = 255

[layouts.icon_size]
x = 81.0
y = 81.0

[layouts.hotkey_color]
r = 255
g = 255
b = 255
a = 255

[layouts.hotkey_offset]
x = 0.0
y = 225.0

[layouts.hotkey_size]
x = 30.0
y = 30.0

[layouts.hotkey_bg_color]
r = 255
g = 255
b = 255
a = 100

[layouts.text_offset]
x = 0.0
y = 0.0

[layouts.count_color]
r = 255
g = 255
b = 255
a = 255

[layouts.name_color]
r = 255
g = 255
b = 255
a = 255

[layouts.name_offset]
x = 0.0
y = 20.0

[[layouts]]
name = "Right Hand"
count_font_size = 20.0

[layouts.element]
repr = 3

[layouts.offset]
x = 446.0
y = 0.0

[layouts.size]
x = 125.0
y = 125.0

[layouts.bg_color]
r = 255
g = 255
b = 255
a = 0

[layouts.icon_color]
r = 200
g = 200
b = 210
a = 255

[layouts.icon_size]
x = 81.0
y = 81.0

[layouts.hotkey_color]
r = 255
g = 255
b = 255
a = 255

[layouts.hotkey_offset]
x = 0.0
y = -225.0

[layouts.hotkey_size]
x = 30.0
y = 30.0

[layouts.hotkey_bg_color]
r = 255
g = 255
b = 255
a = 100

[layouts.text_offset]
x = 0.0
y = 0.0

[layouts.count_color]
r = 255
g = 255
b = 255
a = 255

[layouts.name_color]
r = 255
g = 255
b = 255
a = 255

[layouts.name_offset]
x = 0.0
y = 20.0

[[layouts]]
name = "Ammo"
count_font_size = 20.0

[layouts.element]
repr = 4

[layouts.offset]
x = 0.0
y = 0.0

[layouts.size]
x = 62.0
y = 62.0

[layouts.bg_color]
r = 255
g = 255
b = 255
a = 0

[layouts.icon_color]
r = 200
g = 200
b = 255
a = 255

[layouts.icon_size]
x = 35.0
y = 35.0

[layouts.hotkey_color]
r = 255
g = 255
b = 255
a = 255

[layouts.hotkey_offset]
x = 0.0
y = 0.0

[layouts.hotkey_size]
x = 20.0
y = 20.0

[layouts.hotkey_bg_color]
r = 255
g = 255
b = 255
a = 100

[layouts.text_offset]
x = 0.0
y = 0.0

[layouts.count_color]
r = 255
g = 255
b = 255
a = 255

[layouts.name_color]
r = 255
g = 255
b = 255
a = 255

[layouts.name_offset]
x = 0.0
y = 20.0
